-- Postavljanje sesije na XEPDB1
ALTER SESSION SET CONTAINER = XEPDB1;

-- Kreiranje korisnika
CREATE USER pts IDENTIFIED BY pts
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP;

-- Dodela privilegija
GRANT CONNECT, RESOURCE TO pts;
GRANT CREATE TABLE TO pts;
GRANT CREATE VIEW TO pts;
GRANT CREATE PROCEDURE TO pts;
GRANT CREATE SYNONYM TO pts;
GRANT CREATE SEQUENCE TO pts;
GRANT SELECT ON dba_rollback_segs TO pts;
GRANT SELECT ON dba_segments TO pts;
GRANT UNLIMITED TABLESPACE TO pts;

-- Zatvaranje transakcije
COMMIT;
