-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-01-15 15:11:23 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE
ALTER SESSION SET CONTAINER = XEPDB1;

-- Prijava kao korisnik PTS
ALTER SESSION SET CURRENT_SCHEMA = PTS;


CREATE TABLE Autobus 
    ( 
     idaut  NUMBER  NOT NULL , 
     model  VARCHAR2 (100 CHAR)  NOT NULL , 
     kap    NUMBER , 
     status VARCHAR2 (15 CHAR) CHECK (status IN ('aktivan', 'u kvaru')) 
    ) 
;

ALTER TABLE Autobus 
    ADD CONSTRAINT Autobus_PK PRIMARY KEY ( idaut ) ;

CREATE TABLE Cena 
    ( 
     idcen   NUMBER  NOT NULL , 
     vazidoc DATE  NOT NULL , 
     vaziodc DATE  NOT NULL , 
     cena    NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Cena 
    ADD CONSTRAINT Cena_PK PRIMARY KEY ( idcen ) ;

CREATE TABLE Detalji_povere_autobusa 
    ( 
     idpova   NUMBER  NOT NULL , 
     datvozod DATE  NOT NULL , 
     davozdo  DATE  NOT NULL , 
     idaut    NUMBER  NOT NULL , 
     idrad    NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Detalji_povere_autobusa 
    ADD CONSTRAINT Detalji_povere_autobusa_PK PRIMARY KEY ( idpova ) ;

CREATE TABLE Detalji_povere_linije 
    ( 
     idpovli  NUMBER  NOT NULL , 
     datlinod DATE  NOT NULL , 
     datlindo DATE  NOT NULL , 
     idlin    NUMBER  NOT NULL , 
     idrad    NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Detalji_povere_linije 
    ADD CONSTRAINT Detalji_povere_linije_PK PRIMARY KEY ( idpovli ) ;

CREATE TABLE Dolazak 
    ( 
     iddolaz  NUMBER  NOT NULL , 
     datdolaz DATE  NOT NULL , 
     idstan   NUMBER  NOT NULL , 
     idaut    NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Dolazak 
    ADD CONSTRAINT Dolazak_PK PRIMARY KEY ( iddolaz ) ;

CREATE TABLE Karta 
    ( 
     idkar  NUMBER  NOT NULL , 
     datkup DATE  NOT NULL , 
     vazido DATE  NOT NULL , 
     idput  NUMBER , 
     idcen  NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Karta 
    ADD CONSTRAINT Karta_PK PRIMARY KEY ( idkar ) ;

CREATE TABLE Linija 
    ( 
     idlin  NUMBER  NOT NULL , 
     nazlin VARCHAR2 (50 CHAR)  NOT NULL , 
     povr   NUMBER , 
     poc    NUMBER  NOT NULL , 
     kraj   NUMBER  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX Linija__IDX ON Linija 
    ( 
     povr ASC 
    ) 
;

ALTER TABLE Linija 
    ADD CONSTRAINT Linija_PK PRIMARY KEY ( idlin ) ;

CREATE TABLE Putnik 
    ( 
     idput    NUMBER  NOT NULL , 
     imeput   VARCHAR2 (25 CHAR)  NOT NULL , 
     przput   VARCHAR2 (25 CHAR)  NOT NULL , 
     brtelput VARCHAR2 (15 CHAR) , 
     mailput  VARCHAR2 (255 CHAR) 
    ) 
;

ALTER TABLE Putnik 
    ADD CONSTRAINT Putnik_PK PRIMARY KEY ( idput ) ;

CREATE TABLE Radnik 
    ( 
     idrad  NUMBER  NOT NULL , 
     ime    VARCHAR2 (25 CHAR)  NOT NULL , 
     prz    VARCHAR2 (25 CHAR)  NOT NULL , 
     brtel  VARCHAR2 (15 BYTE)  NOT NULL , 
     mail   VARCHAR2 (255 CHAR)  NOT NULL , 
     mbr    NUMBER  NOT NULL , 
     datzap DATE , 
     tiprad VARCHAR2 (10 CHAR)  NOT NULL CHECK (tiprad IN ('mehanicar', 'vozac')) , 
     brdoz  VARCHAR2 (11 CHAR) 
    ) 
;

ALTER TABLE Radnik 
    ADD CONSTRAINT Radnik_PK PRIMARY KEY ( idrad ) ;

ALTER TABLE Radnik 
    ADD CONSTRAINT Radnik_mail_UN UNIQUE ( mail ) ;

ALTER TABLE Radnik 
    ADD CONSTRAINT Radnik_mbr_UN UNIQUE ( mbr ) ;

CREATE TABLE Raspored 
    ( 
     idras   NUMBER  NOT NULL , 
     dan     VARCHAR2 (20 CHAR)  NOT NULL CHECK (dan IN ('cetvrtak', 'nedelja', 'petak', 'ponedeljak', 'sreda', 'subota', 'utorak')) , 
     vrdolaz DATE  NOT NULL , 
     aktivan CHAR (1)  NOT NULL , 
     idlin   NUMBER  NOT NULL , 
     idstan  NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Raspored 
    ADD CONSTRAINT Raspored_PK PRIMARY KEY ( idras ) ;

CREATE TABLE Sadrzi 
    ( 
     idlin  NUMBER  NOT NULL , 
     idstan NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Sadrzi 
    ADD CONSTRAINT Sadrzi_PK UNIQUE ( idlin , idstan ) ;

CREATE TABLE Se_cekira 
    ( 
     iddolaz NUMBER  NOT NULL , 
     idkar   NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Se_cekira 
    ADD CONSTRAINT Se_cekira_PK PRIMARY KEY ( iddolaz, idkar ) ;

CREATE TABLE Servis 
    ( 
     idserv  NUMBER  NOT NULL , 
     datserv DATE  NOT NULL , 
     opis    VARCHAR2 (300 CHAR)  NOT NULL , 
     idaut   NUMBER  NOT NULL , 
     idrad   NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Servis 
    ADD CONSTRAINT Servis_PK PRIMARY KEY ( idserv ) ;

CREATE TABLE Stanica 
    ( 
     idstan  NUMBER  NOT NULL , 
     nazstan VARCHAR2 (100 CHAR)  NOT NULL , 
     sir     NUMBER (9,6) , 
     duz     NUMBER (9,6) 
    ) 
;

ALTER TABLE Stanica 
    ADD CONSTRAINT Stanica_PK PRIMARY KEY ( idstan ) ;

ALTER TABLE Stanica 
    ADD CONSTRAINT Stanica_nazstan_UN UNIQUE ( nazstan ) ;

CREATE TABLE Vozi 
    ( 
     idaut NUMBER  NOT NULL , 
     idrad NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Vozi 
    ADD CONSTRAINT Vozi_PK PRIMARY KEY ( idaut, idrad ) ;


CREATE TABLE Zaduzenje 
    ( 
     idlin NUMBER  NOT NULL , 
     idrad NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Zaduzenje 
    ADD CONSTRAINT Zaduzenje_PKv2 PRIMARY KEY ( idlin, idrad ) ;

ALTER TABLE Zaduzenje 
    ADD CONSTRAINT Zaduzenje_PK UNIQUE ( idrad , idlin ) ;

ALTER TABLE Detalji_povere_autobusa 
    ADD CONSTRAINT Det_pov_bus_Vozi_FK FOREIGN KEY 
    ( 
     idaut,
     idrad
    ) 
    REFERENCES Vozi 
    ( 
     idaut,
     idrad
    ) 
;

ALTER TABLE Detalji_povere_linije 
    ADD CONSTRAINT Det_pov_lin_FK FOREIGN KEY 
    ( 
     idlin,
     idrad
    ) 
    REFERENCES Zaduzenje 
    ( 
     idlin,
     idrad
    ) 
;

ALTER TABLE Dolazak 
    ADD CONSTRAINT Dolazak_Autobus_FK FOREIGN KEY 
    ( 
     idaut
    ) 
    REFERENCES Autobus 
    ( 
     idaut
    ) 
;

ALTER TABLE Dolazak 
    ADD CONSTRAINT Dolazak_Stanica_FK FOREIGN KEY 
    ( 
     idstan
    ) 
    REFERENCES Stanica 
    ( 
     idstan
    ) 
;

ALTER TABLE Karta 
    ADD CONSTRAINT Karta_Cena_FK FOREIGN KEY 
    ( 
     idcen
    ) 
    REFERENCES Cena 
    ( 
     idcen
    ) 
;

ALTER TABLE Karta 
    ADD CONSTRAINT Karta_Putnik_FK FOREIGN KEY 
    ( 
     idput
    ) 
    REFERENCES Putnik 
    ( 
     idput
    ) 
;

ALTER TABLE Linija 
    ADD CONSTRAINT Linija_Linija_FK FOREIGN KEY 
    ( 
     povr
    ) 
    REFERENCES Linija 
    ( 
     idlin
    ) 
;

ALTER TABLE Linija 
    ADD CONSTRAINT Linija_Stanica_FK FOREIGN KEY 
    ( 
     kraj
    ) 
    REFERENCES Stanica 
    ( 
     idstan
    ) 
;

ALTER TABLE Linija 
    ADD CONSTRAINT Linija_Stanica_FKv2 FOREIGN KEY 
    ( 
     poc
    ) 
    REFERENCES Stanica 
    ( 
     idstan
    ) 
;

ALTER TABLE Raspored 
    ADD CONSTRAINT Raspored_Sadrzi_FK FOREIGN KEY 
    ( 
     idlin,
     idstan
    ) 
    REFERENCES Sadrzi 
    ( 
     idlin,
     idstan
    ) 
;

ALTER TABLE Sadrzi 
    ADD CONSTRAINT Sadrzi_Linija_FK FOREIGN KEY 
    ( 
     idlin
    ) 
    REFERENCES Linija 
    ( 
     idlin
    ) 
;

ALTER TABLE Sadrzi 
    ADD CONSTRAINT Sadrzi_Stanica_FK FOREIGN KEY 
    ( 
     idstan
    ) 
    REFERENCES Stanica 
    ( 
     idstan
    ) 
;

ALTER TABLE Se_cekira 
    ADD CONSTRAINT Se_cekira_Dolazak_FK FOREIGN KEY 
    ( 
     iddolaz
    ) 
    REFERENCES Dolazak 
    ( 
     iddolaz
    ) 
;

ALTER TABLE Se_cekira 
    ADD CONSTRAINT Se_cekira_Karta_FK FOREIGN KEY 
    ( 
     idkar
    ) 
    REFERENCES Karta 
    ( 
     idkar
    ) 
;

ALTER TABLE Servis 
    ADD CONSTRAINT Servis_Autobus_FK FOREIGN KEY 
    ( 
     idaut
    ) 
    REFERENCES Autobus 
    ( 
     idaut
    ) 
;

ALTER TABLE Servis 
    ADD CONSTRAINT Servis_Radnik_FK FOREIGN KEY 
    ( 
     idrad
    ) 
    REFERENCES Radnik 
    ( 
     idrad
    ) 
;

ALTER TABLE Vozi 
    ADD CONSTRAINT Vozi_Autobus_FK FOREIGN KEY 
    ( 
     idaut
    ) 
    REFERENCES Autobus 
    ( 
     idaut
    ) 
;

ALTER TABLE Vozi 
    ADD CONSTRAINT Vozi_Radnik_FK FOREIGN KEY 
    ( 
     idrad
    ) 
    REFERENCES Radnik 
    ( 
     idrad
    ) 
;

ALTER TABLE Zaduzenje 
    ADD CONSTRAINT Zaduzenje_Linija_FK FOREIGN KEY 
    ( 
     idlin
    ) 
    REFERENCES Linija 
    ( 
     idlin
    ) 
;


ALTER TABLE Zaduzenje 
    ADD CONSTRAINT Zaduzenje_Radnik_FK FOREIGN KEY 
    ( 
     idrad
    ) 
    REFERENCES Radnik 
    ( 
     idrad
    ) 
;

ALTER TABLE Radnik
ADD CONSTRAINT chk_brdoz_mehanicar CHECK (
    (tiprad = 'mehanicar' AND brdoz IS NULL) OR
    (tiprad = 'vozac' AND brdoz IS NOT NULL)
);


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            16
-- CREATE INDEX                             1
-- ALTER TABLE                             41
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
